version: '2'
services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile
        volumes:
          - ./data:/data
          - ./api:/api:ro
          - ./web/dist:/api/purepage/templates:ro
    web:
        build:
            context: .
            dockerfile: web.dockerfile
        volumes:
          - ./web:/web
    nginx:
        image: daocloud.io/nginx:stable-alpine
        volumes:
          - ./data:/data
          - ./web/dist:/web:ro
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
          - "80:80"
          - "5000:5000"
    db:
        image: rethinkdb:latest
        volumes:
          - ./data/rethinkdb:/data
        ports:
          - "8080:8080"
