version: '2'
services:
    app:
        build: .
        volumes:
         - .:/code
        depends_on:
         - couchdb

    nginx:
        image: nginx:stable-alpine
        volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
         - .:/code
        ports:
         - '5000:80'
        depends_on:
         - app

    couchdb:
        image: klaemo/couchdb:2.0-dev 
        command: --admin=admin:123456 --with-haproxy 
        ports:
         - '5984:5984'
        volumes:
         - ./data/couchdb:/usr/local/var/lib/couchdb

