version: '2'
services:
    web:
        build: .
        ports:
         - '8080:80'
        volumes:
         - .:/code
        depends_on:
         - couchdb

    couchdb:
        image: klaemo/couchdb:2.0-dev 
        command: --admin=admin:123456 --with-haproxy 
        ports:
         - '5984:5984'
        volumes:
         - ./data/couchdb:/usr/local/var/lib/couchdb

