version: '2'
services:
    api:
        build:
          context: .
          dockerfile: api.dockerfile
        volumes:
         - ./api:/api
        depends_on:
         - couchdb
    static:
        build: .
        volumes:
         - .:/code
        network_mode: "host"
        depends_on:
         - couchdb
    nginx:
        image: nginx:stable-alpine
        volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
         - .:/code
        network_mode: "host"
        depends_on:
         - app
    db:
        image: klaemo/couchdb:2.0-dev
        command: --admin=admin:123456 --with-haproxy
        network_mode: "host"
        volumes:
         - ./data/couchdb:/usr/local/var/lib/couchdb
