version: '2'
services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile
        volumes:
           - ./data:/data
           - ./api:/api
           - ./web/dist:/api/purepage/templates
    web:
        build:
            context: .
            dockerfile: web.dockerfile
        volumes:
           - ./web:/web
    nginx:
        image: daocloud.io/nginx:stable-alpine
        volumes:
           - ./web/dist:/web
           - ./data:/data
           - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
           - "5000:80"
    db:
        image: rethinkdb:latest
        volumes:
           - ./data/rethinkdb:/data
        ports:
           - "28015:28015"
           - "6000:8080"
